AWSTemplateFormatVersion: 2010-09-09

Description: This template create an AutoScaling

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - 
        Label: 
          default: "Export VPC Stack Name"
        Parameters:
          - ExportVpcStackName
      -
        Label: 
          default: "Export target-group-Name"
        Parameters:
          - ExportALBtargetARN

Parameters:

  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String

  # ExportALBtargetARN:
  #   Description : The name of ALB-ARN
  #   Type: String

Resources:
#Create an Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyApplicationLoadBalancer
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-SecurityGroup
      Subnets: 
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet1
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet2

#Create a Listener on Port 80
  ALBListenerNoSslCertificate:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        #- RedirectConfig:
         #   Host: '#{host}'
          #  Path: '/#{path}'
           # Port: '443'
            #Protocol: HTTPS
            #StatusCode: HTTP_301
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP



# Create a Target Group
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: 200,302
      Name: MyWebServers2
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !Ref EC2Instance1
          Port: 80
        - Id: !Ref EC2Instance2
          Port: 80
      TargetType: instance    
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-VPC

  myLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    #DependsOn: ApplicationLoadBalancer
    Properties:
      LaunchConfigurationName: first-launch-configuration
      ImageId: ami-090717c950a5c34d3
      SecurityGroups: 
          - Fn::ImportValue: !Sub ${ExportVpcStackName}-SecurityGroup
      InstanceType: t2.micro
      KeyName:  test-orgon
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            apt  update -y
            apt install apache2 -y
            echo "Healthy1" > /var/www/html/index.html
            systemctl start apache2

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    #DependsOn: myLaunchConfig
    Properties:
      AutoScalingGroupName: First-auto-scaling
      MinSize: 1
      MaxSize: 5
      DesiredCapacity: 2 
      HealthCheckGracePeriod: 300
      LaunchConfigurationName: !Ref myLaunchConfig
      VPCZoneIdentifier:
           - Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet1
           - Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet2
      TargetGroupARNs:
           -  !Ref ALBTargetGroup


  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet1
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-SecurityGroup
      KeyName: test-orgon
      ImageId: ami-090717c950a5c34d3
      Tags:
        - Key: Name
          Value: EC2 | PublicSubnet1
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            apt  update -y
            apt install  -y apache2
            echo "Healthy1" > /var/www/html/index.html
            systemctl start apache2
     

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet2
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-SecurityGroup
      KeyName: test-orgon
      ImageId: ami-090717c950a5c34d3
      Tags:
        - Key: Name
          Value: EC2 | PublicSubnet2
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            apt update -y
            apt install -y apache2
            echo "Healthy" > /var/www/html/index.html
            systemctl start apache2

Outputs:
#Export VPC ID
  AutoScaling:
    Description: AutoScaling-grp
    Export:
      Name: myASGs
    Value: !Ref myASG
