AWSTemplateFormatVersion: "2010-09-09"
Description: 
  AWS CloudFormation  for  Dynamo Db
Parameters:
  Attributename:
     Type: String
     Description: A name for the attribute.
    
  Attributetype:
      Type: String
      Default: String
      AllowedValues:
         - Binary
         - Number
         - String

  IndexName:
      Type: String
      Description : The name of the global secondary index. The name must be unique among all other indexes on this table.

  Readcapacityunitsindex:
    Description: Enter the read capacity  provisioned  Values.
    Type: Number

  Writecapacityunitsindex:
      Description: Enter the write  capacity  provisioned  Values.
      Type: Number

  Billingmode:
      Description: how we are charged for read and write throughput .
      Type: String
      Default: PROVISIONED
      AllowedValues:
        - PROVISIONED 
        - PAY_PER_REQUEST 
    
  Projectiontype:
       Description: The set of attributes that are projected into the index
       Type: String
       Default: ALL
       AllowedValues:
        - KEYS_ONLY 
        - INCLUDE 
        - ALL 


Resources:
  Dynamo:
   Type: AWS::DynamoDB::Table
   Properties: 
     AttributeDefinitions:
       - AttributeName: !Ref Attributename
       - AttributeType: !Ref Attributetype
     BillingMode: !Ref Billingmode
     GlobalSecondaryIndexes:
       - IndexName: !Ref IndexName
         ProvisionedThroughput:
          ReadCapacityUnitsindex: !Ref Readcapacityunitsindex
          WriteCapacityUnitsindex: !Ref Writecapacityunitsindex
          Projection:
            ProjectionType: !Ref Projectiontype
     ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
     TableName: "myTableName"  
  

