AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation  for Gateway Load Balancer (GWLB)
Metadata:
  RevisionDate: 26-November-2021
Parameters:
  GwlbName:
    Description: Gateway Load Balancer Name
    Type: String
    AllowedPattern: '(^[a-z0-9-]*)$'

  VpcId:
    Description: VPC Id to associate with target group. (e.g. vpc-a123baa3 )
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: Must be a valid VPC Id

  GwlbSubnets:
    Description: List of subnets to associate with your GWLB.  (e.g., ['subnet-123a351e', subnet-456a351e])
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: Must be a valid list of subnet ids


  HealthProtocol:
    Description: The protocol the appliane gateway uses when performing health checks on targets.
    Type: String
    Default: TCP
    AllowedValues: ['TCP', 'HTTP', 'HTTPS']
    ConstraintDescription: Must be a valid health check protocol

  GLBdeletionprotection:
    Description: Specify whether the deletion protection is enabled or disabled
    Default: True
    Type: String
    AllowedValues:
      - True
      - False

  GLBcrosszone:
    Description: Specify whether cross-zone load balancing is to be enabled
    Default: True
    Type: String
    AllowedValues:
       - True
       - False


  HealthPort:
    Description:  The port the load balancer uses when performing health checks on targets. For Gateway Load Balance specify port other then the traffic port.
    Type: String
    Default: '80'
    ConstraintDescription: Must be a valid health check port

  TargetGroupName:
    Description: Target Group Name
    Type: String
    Default: targetglbw
    ConstraintDescription: Must be a valid target group name

  HealthCheckIntervalSeconds:
    Description:  Health checks of an individual target ,If the target group protocol is GENEVE, the default is 10 seconds
    Type: Number
    Default: 10
    MinValue: 5
    MaxValue: 300

  HealthCheckTimeoutseconds:
    Description: Time seconds, during which no response from a target means a failed health check.
    Type: Number 
    Default: 5
    MinValue: 2
    MaxValue: 120

  HealthyThresholdcount:
    Default: 5
    Type: Number
    MinValue: 2
    MaxValue: 120

  UnhealthyThresholdCount:
    Description: The number of consecutive health check failures required before considering a target unhealthy, If the target group protocol is GENEVE, the default is 3
    Default: 3
    Type: Number
    MinValue: 2
    MaxValue: 10

  TGderegistrationdelay: 
    Type: Number
    Description:  Amount of time, in seconds, for Load Balancer to wait before changing the state of a deregistering target from draining to unused.

  
  Owner: 
    Description: Email Id of the resource owner
    Type: String

  AppName:
    Description: Enter the appname
    Type: String

  Env:
   Description: Name of the environment
   Type: String
   Default: DEV
   AllowedValues:
        - DEV 
        - PRD
        - DR
        - SB
        - PT
  Zone:
    Description: To identify the application is internal or internet facing
    Type: String
    Default: Internal
    AllowedValues:
      - Internal
      - Internet

  CostCentre:
    Description: Cost Centre Code
    Type: String

  BusinessUnits:
    Description: Business Unit Code
    Type: String

  MapMigrated:
    Description: The map migrated
    Type: String

  AwsMigrationProjectId:
    Description: Enter the  aws migration project id
    Type: String

  
  

Resources:
  Gwlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      #Name: !Ref GwlbName
      Type: gateway
      Subnets: !Ref GwlbSubnets
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled 
          Value: !Ref GLBdeletionprotection
        - Key: load_balancing.cross_zone.enabled
          Value:  !Ref GLBcrosszone
      Tags:
          
        - Key: Name
          Value: !Ref GwlbName  
      
        - Key: Owner
          Value: !Ref Owner

        - Key: AppName
          Value: !Ref AppName

        - Key: Env
          Value: !Ref Env

        - Key: Zone
          Value: !Ref Zone

        - Key: CostCentre
          Value: !Ref CostCentre

        - Key: BusinessUnits
          Value: !Ref BusinessUnits

        - Key: map-migrated
          Value: !Ref MapMigrated

        - Key: aws-migration-projectid
          Value: !Ref AwsMigrationProjectId

        - Key: StackId
          Value: !Ref  "AWS::StackName"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupName
      Port: 6081
      Protocol: GENEVE
      HealthCheckPort: !Ref HealthPort
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      HealthCheckProtocol: !Ref HealthProtocol
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeoutseconds
      HealthyThresholdCount: !Ref HealthyThresholdcount
      UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: !Ref TGderegistrationdelay
      VpcId: !Ref VpcId
      TargetType: instance
      Tags:

        - Key: Owner
          Value: !Ref Owner

        - Key: AppName
          Value: !Ref AppName

        - Key: Env
          Value: !Ref Env

        - Key: Zone
          Value: !Ref Zone

        - Key: CostCentre
          Value: !Ref CostCentre

        - Key: BusinessUnits
          Value: !Ref BusinessUnits

        - Key: map-migrated
          Value: !Ref MapMigrated

        - Key: aws-migration-projectid
          Value: !Ref AwsMigrationProjectId

        - Key: StackId
          Value: !Ref  "AWS::StackName"
        

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref Gwlb


  Endpointgatewayloadbalancer:
    Type: AWS::EC2::VPCEndpointService
    Properties:
        AcceptanceRequired: False
        GatewayLoadBalancerArns: 
         - !Ref Gwlb
        
        

